### ISSUE TITLE
Create a powerush shell

### ISSUE THREAD

**Issue by MoltenCoreDev** [NOperatingSystem/NOperatingSystem#1]
Just create a basic shitty shell harder to make then say. Who wants to document it definetly not me

**Comment by mugman174** [comment]
How about implementing busybox?
Like, you could have it load busybox from another partition, or just copy some GRUB code to do that.

**Comment by MoltenCoreDev** [comment]
It needs to do shit that's all, can execute commands

**Comment by MoltenCoreDev** [comment]
Got user input working pushing to playground

**Comment by mugman174** [comment]
It works now! type `c` for "death command" or smth

**Comment by MoltenCoreDev** [comment]
Created on unstable branch. Closing the issue.

**Comment by mugman174** [comment]
Work in progress in master branch

**Comment by mugman174** [comment]
Multichar shell finalized on master branch 😄
