### ISSUE TITLE
Backspace and many other keys show random unicode chars, like "⌂"

### ISSUE THREAD

**Issue by mugman174** [NOperatingSystem/NOperatingSystem#10]
# Someone fix this, or tell us how to.

**Comment by MoltenCoreDev** [comment]
Can't reproduce.

**Comment by mugman174** [comment]
> Can't reproduce.

😐 Press `s` and press backspace. (Maybe it's just a `mintty`/`putty`/`cmd` issue idk)

**Comment by MoltenCoreDev** [comment]
![image](https://user-images.githubusercontent.com/54597045/105897904-13f1e180-6019-11eb-8291-959f1c836ede.png)
Trying to reproduce leaves this:

**Comment by mugman174** [comment]
Different Unicode characters, but same problem.
