### ISSUE TITLE
Not the Largest Operating System in the World

### ISSUE THREAD

**Issue by caughtquick** [NOperatingSystem/NOperatingSystem#14]
Doesn't beat windows, linux, and even MacOS for the throne. How could it not

**Comment by mugman174** [comment]
- It's more of a boot loader and less of a real operating system
- It's not meant to be as big as Linux, Windows, and macOS. It's mostly a meme os.
- It's programmed in Assembler, real mode, unlike other systems which usually utilize a kernel to load the file system and system binaries.

**Comment by MoltenCoreDev** [comment]
REEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
