### ISSUE TITLE
no updates

### ISSUE THREAD

**Issue by SkyBlockDev** [NOperatingSystem/NOperatingSystem#24]
smh my who update mnan

**Comment by mugman174** [comment]
Yea it’s sad. @jdadonut is supposed to be working on entering 32 bit protected mode but it doesn’t work. If you/anyone know(s) pls PR.

**Comment by mugman174** [comment]
If you want, we have a discord [here](https://discord.gg/KaQJ6pqrPF).

**Comment by SkyBlockDev** [comment]
ill make a pr brb

**Comment by mugman174** [comment]
It's still not entering 32-bit mode from what I see...
![Booting from Hard Disk...
noOS: Started in 16-bit real mode, Loading...](https://user-images.githubusercontent.com/53713683/108094242-75630a00-7033-11eb-87e0-a8bc0273b141.png)

**Comment by jdadonut** [comment]
p

> 
> 
> Yea it’s sad. @jdadonut is supposed to be working on entering 32 bit protected mode but it doesn’t work. If you/anyone know(s) pls PR.

yeah, every method ive seen to get into 32bpm just bootloops the emulator
