### ISSUE TITLE
spanosh installation halp

### ISSUE THREAD

**Issue by ghost** [NOperatingSystem/NOperatingSystem#6]
ññññññññññññññ

**Comment by k6d** [comment]
how to add tags aaaa

**Comment by mugman174** [comment]
No entiendo lo que quieres decir.
||[Google Translate](http://translate.google.com)||

**Comment by MoltenCoreDev** [comment]
hablo englesa taco eta just install it

**Comment by iiTrauma** [comment]
w
a
t

**Comment by MoltenCoreDev** [comment]
who tf closed this issue

**Comment by mugman174** [comment]
Constrúyalo con ./build.bat para Windows o ./build.sh para Linux o mac. Ejecútelo con QEMU.

[Google Translate](https://translate.google.com/?sl=en&tl=es&text=Build%20it%20with%20.%2Fbuild.bat%20for%20Windows%20or%20.%2Fbuild.sh%20for%20Linux%20or%20mac.%20Run%20it%20with%20QEMU.&op=translate)

**Comment by MoltenCoreDev** [comment]
> Constrúyalo con ./build.bat para Windows o ./build.sh para Linux o mac. Ejecútelo con QEMU.
> 
> [Google Translate](https://translate.google.com/?sl=en&tl=es&text=Build%20it%20with%20.%2Fbuild.bat%20for%20Windows%20or%20.%2Fbuild.sh%20for%20Linux%20or%20mac.%20Run%20it%20with%20QEMU.&op=translate)

no lol?

**Comment by iiTrauma** [comment]
> Constrúyalo con ./build.bat para Windows o ./build.sh para Linux o mac. Ejecútelo con QEMU.
> 
> [Google Translate](https://translate.google.com/?sl=en&tl=es&text=Build%20it%20with%20.%2Fbuild.bat%20for%20Windows%20or%20.%2Fbuild.sh%20for%20Linux%20or%20mac.%20Run%20it%20with%20QEMU.&op=translate)

hi 1337 hacker how to install on prime os?

**Comment by MoltenCoreDev** [comment]
you click the button and it installs

**Comment by MoltenCoreDev** [comment]
oh sorry espanol
le taco clicko on do installo buttono and installa
